# Generated by Django 4.1.7 on 2023-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="articles",
            name="document_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
