# Generated by Django 4.1.7 on 2023-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_user_tg_username_alter_articles_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
