# Generated by Django 4.1.7 on 2023-03-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_user_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramHash",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hash", models.CharField(max_length=255)),
                ("telegram_user_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="tg_username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
