# Generated by Django 4.1.7 on 2023-03-09 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_telegramhash_remove_user_tg_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramhash",
            name="telegram_user_id",
        ),
        migrations.AddField(
            model_name="telegramhash",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_user_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Telegram user ID"),
        ),
    ]
