# Generated by Django 4.1.7 on 2023-03-09 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_remove_telegramhash_telegram_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramhash",
            name="user",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
