# Generated by Django 4.1.7 on 2023-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_telegramhash_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_user_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name="Telegram user ID"),
        ),
    ]
