# Generated by Django 4.1.9 on 2023-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_user_telegram_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="document_file",
            field=models.FileField(null=True, upload_to="articles/"),
        ),
    ]
